[package]
name = "conchy"
version = "0.1.0"
authors = ["Francis <francis.screene@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rocket = "0.4.5"
log = "0.4"